apiVersion: v1
data:
  agent.conf: |
    {
      "agent": {
        "data_dir": "/run/spire",
        "log_level": "info",
        "server_address": "spire-aws-server.spire",
        "server_port": "8081",
        "socket_path": "/run/spire/agent-sockets/spire-agent.sock",
        "trust_bundle_path": "/run/spire/bundle/bundle.crt",
        "trust_domain": "aws.com"
      },
      "health_checks": {
        "bind_address": "0.0.0.0",
        "bind_port": "9980",
        "listener_enabled": true,
        "live_path": "/live",
        "ready_path": "/ready"
      },
      "plugins": {
        "KeyManager": [
          {
            "memory": {
              "plugin_data": null
            }
          }
        ],
        "NodeAttestor": [
          {
            "k8s_psat": {
              "plugin_data": {
                "cluster": "aws-cluster"
              }
            }
          }
        ],
        "WorkloadAttestor": [
          {
            "k8s": {
              "plugin_data": {
                "disable_container_selectors": false,
                "skip_kubelet_verification": true
              }
            }
          }
        ],
        "SVIDStore": [
          {
            "aws_secretsmanager": {
              "plugin_data": {
                "access_key_id": "ACCESS_KEY_ID",
                "secret_access_key": "SECRET_ACCESS_KEY",
                "region": "us-east-1"
              }
            }
          }
        ]
      }
    }
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: spire-aws
    meta.helm.sh/release-namespace: spire
  labels:
    app.kubernetes.io/managed-by: Helm
  name: spire-aws-agent
  namespace: spire
