global:
  spire:
    trustDomain: aws.com
    clusterName: aws-cluster

    #spire-server:
    #  controllerManager:
    #    enabled: true
    #

spire-server:
  controllerManager:
    enabled: false

spire-agent:
  customPlugins:
    svidStore:
    - aws_secretsmanager:
        plugin_data:
          access_key_id: "AKI"
          secret_access_key: "iKIFZkGZ"
          region: "us-east-1"
          #
          #
          #---
          #plugin:
          #  SVIDStore:
          #  - aws_secretsmanager:
          #      plugin_data:
          #        access_key_id: ACCESS_KEY_ID
          #        secret_access_key: SECRET_ACCESS_KEY
          #        region: us-east-1
          #
