name: Helm Chart CI

on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, reopened]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  unittests:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Run unit tests
        run: script -e -c make
