---
apiVersion: v1
kind: Service
metadata:
  name: {{ default (printf "%s-server" .Release.Name) (.Values.server).serviceName | quote }}
  namespace: {{ $.Release.Namespace | quote }}
spec:
  type: ClusterIP
  selector:
    app: {{ $.Release.Name }}-server
  ports:
    - port: {{ default 8081 (.Values.server).servicePort }}
      protocol: "TCP"
